### ISSUE TITLE
error when combining transcripts

### ISSUE THREAD

**Issue by jeremymcrae** [jeremymcrae/denovonear#1]
Occasionally, we can get an error when combining transcripts

``` python
import tempfile

from denovonear.load_gene import construct_gene_object
from denovonear.ensembl_requester import EnsemblRequest

cache = tempfile.TemporaryDirectory()
ensembl = EnsemblRequest(cache.name, 'grch37')

tx1 = construct_gene_object(ensembl, 'ENST00000432832')
tx2 = construct_gene_object(ensembl, 'ENST00000344777')
tx3 = construct_gene_object(ensembl, 'ENST00000553600')

combined = tx1 + tx2

# this gives an error! Only occurs after tx1 and tx2 have been combined
combined = tx3 + combined

# but this does not, even though they should be identical
combined = combined + tx3
```

The error given is 
``` 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "denovonear/transcript.pyx", line 221, in denovonear.transcript.Transcript.__add__
  File "denovonear/transcript.pyx", line 326, in denovonear.transcript.Transcript.add_genomic_sequence
IndexError: basic_string::substr
```

**Comment by jeremymcrae** [comment]
fixed by c194974c91d29a0658f0a313324f7190911c4bbe
